export enum ValidateProfileError {
    INCORRECT_USERNAME = "INCORRECT_USERNAME",
    INCORRECT_AGE = "INCORRECT_AGE",
    INCORRECT_CITY = "INCORRECT_CITY",
    NO_DATA = "NO_DATA",
    SERVER_ERROR = "SERVER_ERROR"
}