name: ci🚀
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install packages
        uses: npm install
      - name: build prod version
        uses: npm run build:prod
      - name: lint ts
        uses: npm run lint:ts
      - name: lint scss
        uses: npm run lint:scss
      - name: testing unit
        uses: npm run test:unit